### ISSUE TITLE
For a what you disable debug mode?

### ISSUE THREAD

**Issue by tarampampam** [zeuxisoo/php-slim-whoops#14]
```php
...

class WhoopsMiddleware extends Middleware {
    public function call() {
        $app = $this->app;

        if ($app->config('debug') === true) {
            // Switch to custom error handler by disable debug
            $app->config('debug', false);
//          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

...
```

Why you make this? Debug mode is important for other components!

**Comment by zeuxisoo** [comment]
Your question is related slim framework 2.x version and it change history. In the latest version of slim, you can look in to [this line](https://github.com/slimphp/Slim/blob/2.x/Slim/Slim.php#L1296). Also. If you want more information about this question, you may need to review the slim workflow.

**Comment by danielemontesi** [comment]
@zeuxisoo , please could you give us a short explanation ? Thank you.

**Comment by zeuxisoo** [comment]
@danielemontesi Thank you for your question.

This option is only needed for Slim 2.x version. In Slim 2.x, it will add the default exception middleware on top of middleware stack if the debug mode is enabled. So, we need to disable this action before adding the custom middleware

If you want more information, please see my previous comment and review the Slim 2.x code. it is related slim how to process the web request.
