### ISSUE TITLE
[again] Call to undefined method Closure::getContainer()

### ISSUE THREAD

**Issue by concept-core** [zeuxisoo/php-slim-whoops#16]
This time I am mostly certain it is my fault.
But I am using a class to get whoops to work in slim.

Would you happen to know how to solve this issue ? 

Here is my file : 
https://github.com/concept-core/laraslim/blob/master/base/AppStarter.php#L47-L72

**Comment by zeuxisoo** [comment]
Please reference to the closed issue #12  or PR #15

**Comment by concept-core** [comment]
Got it working now :) 
I was using the custom error handler first but that did not work.
Loading it directly in as middleware.
