### ISSUE TITLE
How to add middleware to phpErrorHandler?

### ISSUE THREAD

**Issue by visualcookie** [zeuxisoo/php-slim-whoops#17]
I know, when placing the Middleware call into my src/middleware.php file, it will automatically replace Slim's error message with Whoops (haven't tested yet). But sometimes, I run into trouble with PHP errors.

Is there a way to replace them with Whoops too? If so, how? Haven't found it anywhere.

EDIT: Tried the rest, to see if the Error Handler is replaced, but it's not. Doing it like so: `$app->response()->status(500);`

This is my public/index.php file:
```
<?php

require __DIR__ . '/../vendor/autoload.php';

session_start();

// Instantiate the app
$settings = require __DIR__ . '/../src/settings.php';
$app = new \Slim\App($settings);

// Set up dependencies
require __DIR__ . '/../src/dependencies.php';

// Register middleware
require __DIR__ . '/../src/middleware.php';

// Register routes
require __DIR__ . '/../src/routes.php';

// Run app
$app->run();
```

In the src/middleware.php is the Middleware call as in the Readme `$app->add(new \Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware($app));`.

**Comment by zeuxisoo** [comment]
In this stage, the middleware only replaces the default `errorHandler` container not `phpErrorHandler`. The `phpErrorHandler` is for PHP7.

And if your application breaks the lifecycle of slim middleware. it will not trigger this middleware that why you cannot see the whoop error. For example, the program throws exception and without a handle.

**Comment by visualcookie** [comment]
Amazing, will try that out as soon as I'm back. 👍
