### ISSUE TITLE
getContentCharset() is broking. branch 0.7.x

### ISSUE THREAD

**Issue by kaxias** [zeuxisoo/php-slim-whoops#25]
https://github.com/zeuxisoo/php-slim-whoops/blob/0.7.x/src/Zeuxisoo/Whoops/Slim/WhoopsGuard.php#L52

getContentCharset() is broked or it is been removed. I'm not sure.

sorry for bad English.

**Comment by zeuxisoo** [comment]
Sorry for the late reply. 

The `getContentCharset` method comes from [Slim-Http Decorators][1]. This package is recommended to use in Slim Framework,  and this method is not part of the PSR-7 standard reference to [Slim-Http Source][2]

[1]: https://github.com/slimphp/Slim/tree/4.x#slim-http-decorators
[2]: https://github.com/slimphp/Slim-Http/blob/master/src/ServerRequest.php#L423
