### ISSUE TITLE
Add slim to required dependencies

### ISSUE THREAD

**Issue by ghost** [zeuxisoo/php-slim-whoops#26]
I think is better to add slim in the required dependencies.
I've slim 3. When i require this package i get the latest version for slim 4 instead of the slim 3 compatible version.
Thanks.

**Comment by zeuxisoo** [comment]
The Slim package already in the `require-dev` section, So, May I knew what do you mean that?

If you are using Slim 3, Please use the `0.6.*` version (Branch 0.6.x). You can find out more information in the README.md

**Comment by ghost** [comment]
You're right, thanks.
