### ISSUE TITLE
Support PHP8.0

### ISSUE THREAD

**Issue by i4M1k0SU** [zeuxisoo/php-slim-whoops#29]
Does it have any plan to support PHP8.0?

**Comment by zeuxisoo** [comment]
May I know what problems did you running under PHP 8.0? 

Since I did not found any problem running tests under PHP 8.0. So can you mind to explain your situation for me to reproduce it?

**Comment by i4M1k0SU** [comment]
The installation was not possible because 8.0 is not written in the composer.json.

I forced the installation and ran it and found no problems with the operation itself.

**Comment by zeuxisoo** [comment]
I have added the 8.0 version into the require section in the composer.json. Thank you for your help

**Comment by i4M1k0SU** [comment]
Thank you for your support.
