### ISSUE TITLE
How I can enable/disable the JsonResponseHandler ?

### ISSUE THREAD

**Issue by borgogelli** [zeuxisoo/php-slim-whoops#8]
How I can enable/disable the JsonResponseHandler ?

Thank you in advance

Greeting from Italy

Andrea

**Comment by zeuxisoo** [comment]
Currently, This option is not supported. Why do you need this option?

**Comment by borgogelli** [comment]
I can't understand the following code...

<code>
class WhoopsMiddleware extends Middleware { 
....
  $app->container->singleton('whoopsJsonResponseHandler', function() {
                $handler = new JsonResponseHandler();
                $handler->onlyForAjaxRequests(true);
                return $handler;
            });
....
</code>

is the JsonResponseHandler always available ?

we like to use two handlers like in the following code:

$whoops->pushHandler(new Whoops\Handler\PrettyPageHandler);
$whoops->pushHandler(new Whoops\Handler\JsonResponseHandler)

**Comment by zeuxisoo** [comment]
By default, The JsonResponseHandler is always available when you added this middleware.

If the user request is AJAX and got exception. It will handled by JsonResponseHandler.
If the user request is **Not** AJAX and got exception. It will **Not** handled by JsonResponseHandler.

Also, The PrettyPageHandler is for the default case.
