### ISSUE TITLE
Fatal error: Cannot use object of type Closure as array

### ISSUE THREAD

**Issue by nhymxu** [zeuxisoo/php-slim-whoops#9]
Fatal error: Cannot use object of type Closure as array in vendor\zeuxisoo\slim-whoops\src\Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware.php on line 12

with Slim 3

**Comment by zeuxisoo** [comment]
I can't reproduce this case in my environment

- filp/whoops (1.1.5)
- slim/slim dev-develop (5d2b86f)

Are you using the latest `0.4.0` branch with Slim 3?

**Comment by nhymxu** [comment]
Thanks, after force composer reinstall all component, it's work
